/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

//import conexion.conexion;
import Modelo.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.*;
import java.sql.PreparedStatement;


/**
 *
 * @author laura.giraldot
 */
public class EstudianteNuevo extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarTipoEstudiante
     */
        Conexion con = new Conexion();
        Connection cn;
        Statement st;
        ResultSet rs;
        private String ced;
    
    public EstudianteNuevo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ap = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        diagnostico = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        estrato = new javax.swing.JTextField();
        anno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        generootro = new javax.swing.JCheckBox();
        discapsi = new javax.swing.JCheckBox();
        discapno = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        generomasculino = new javax.swing.JCheckBox();
        generofemenino = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        Inscribir = new javax.swing.JButton();
        grado = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        registro.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 550, 80));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonretroceso.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 105, 167));
        jLabel3.setText("Digite la información y presione la tecla \"Inscribir\"");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Documento de Identidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        ap.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ap.setForeground(new java.awt.Color(102, 102, 102));
        ap.setText("Apellidos:");
        getContentPane().add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Edad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Diagnóstico:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Estrato Socioeconómico:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Grado Escolar:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        diagnostico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        diagnostico.setForeground(new java.awt.Color(102, 102, 102));
        diagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoActionPerformed(evt);
            }
        });
        getContentPane().add(diagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 350, 100));

        nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 350, -1));

        edad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        edad.setForeground(new java.awt.Color(102, 102, 102));
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 80, -1));

        estrato.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        estrato.setForeground(new java.awt.Color(102, 102, 102));
        estrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estratoActionPerformed(evt);
            }
        });
        getContentPane().add(estrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 80, -1));

        anno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        anno.setForeground(new java.awt.Color(102, 102, 102));
        anno.setText("AAAA");
        anno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annoMouseClicked(evt);
            }
        });
        anno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annoActionPerformed(evt);
            }
        });
        getContentPane().add(anno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 80, -1));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 10, 490));

        generootro.setBackground(new java.awt.Color(255, 255, 255));
        generootro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        generootro.setForeground(new java.awt.Color(102, 102, 102));
        generootro.setText("Otro");
        generootro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generootroActionPerformed(evt);
            }
        });
        getContentPane().add(generootro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        discapsi.setBackground(new java.awt.Color(255, 255, 255));
        discapsi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        discapsi.setForeground(new java.awt.Color(102, 102, 102));
        discapsi.setText("Si");
        getContentPane().add(discapsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, -1, -1));

        discapno.setBackground(new java.awt.Color(255, 255, 255));
        discapno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        discapno.setForeground(new java.awt.Color(102, 102, 102));
        discapno.setText("No");
        discapno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discapnoActionPerformed(evt);
            }
        });
        getContentPane().add(discapno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Género:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        generomasculino.setBackground(new java.awt.Color(255, 255, 255));
        generomasculino.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        generomasculino.setForeground(new java.awt.Color(102, 102, 102));
        generomasculino.setText("Masculino");
        getContentPane().add(generomasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        generofemenino.setBackground(new java.awt.Color(255, 255, 255));
        generofemenino.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        generofemenino.setForeground(new java.awt.Color(102, 102, 102));
        generofemenino.setText("Femenino");
        generofemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generofemeninoActionPerformed(evt);
            }
        });
        getContentPane().add(generofemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Certificado de Discapacidad");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        documento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        documento.setForeground(new java.awt.Color(102, 102, 102));
        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });
        getContentPane().add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 350, -1));

        Inscribir.setBackground(new java.awt.Color(0, 105, 167));
        Inscribir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Inscribir.setForeground(new java.awt.Color(255, 255, 255));
        Inscribir.setText("Inscribir");
        Inscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InscribirMouseClicked(evt);
            }
        });
        Inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirActionPerformed(evt);
            }
        });
        getContentPane().add(Inscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 230, 40));

        grado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        grado.setForeground(new java.awt.Color(102, 102, 102));
        grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradoActionPerformed(evt);
            }
        });
        getContentPane().add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 80, -1));

        dia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        dia.setForeground(new java.awt.Color(102, 102, 102));
        dia.setText("DD");
        dia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diaMouseClicked(evt);
            }
        });
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 80, -1));

        mes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        mes.setForeground(new java.awt.Color(102, 102, 102));
        mes.setText("MM");
        mes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesMouseClicked(evt);
            }
        });
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 80, -1));

        apellidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        apellidos.setForeground(new java.awt.Color(102, 102, 102));
        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });
        getContentPane().add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 350, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonavanzar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jButton1ComponentHidden(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 660, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Nombres:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        SeleccionarTipoEstudiante est;
        est = new SeleccionarTipoEstudiante();
        est.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void diagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosticoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void estratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estratoActionPerformed

    private void generootroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generootroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generootroActionPerformed

    private void discapnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discapnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discapnoActionPerformed

    private void generofemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generofemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generofemeninoActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    private void InscribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscribirMouseClicked
    
    }//GEN-LAST:event_InscribirMouseClicked

    private void InscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirActionPerformed
        
        String documento_t = documento.getText();
        this.ced = documento.getText();
        String nombre_t = nombre.getText();
        String apellidos_t = apellidos.getText();
        String edad_t = edad.getText();
        String estrato_t = estrato.getText();
        String grado_t = grado.getText();
        String diagnostico_t = diagnostico.getText();
        String dia_t = dia.getText();
        String mes_t = mes.getText();
        String anno_t = anno.getText();
//        String genero_t = null;
//        String cdisc = null;
        String genero_t = null;
        String cdisc = null;
        
        if(generomasculino.isSelected()){
            genero_t = "Maculino";
        }
        if(generofemenino.isSelected()){
            genero_t = "Femenino";
        }
        if(generootro.isSelected()){
            genero_t = "Otro";
        }
        if(discapsi.isSelected()){
            cdisc = "1";
        }
        if(discapno.isSelected()){
            cdisc = "0";
        }
        
        //System.out.println("Documento: " + documento_t + ", Nombre: " + nombre_t + ", Apellidos:" + apellidos_t + ", Edad: " + edad_t + ", Estrato: " + estrato_t + ", Grado: " + grado_t + ", Diagnostico: " + diagnostico_t);// + ", Sexo: " + sexo_t);
        
        // Texto para SQL
        //String query_insert = "INSERT INTO `datos`(`Documento`,`Nombre`,`Apellidos`,`Edad`,`Género`,`Estrato`,`Grado`,`CertifDiscapacidad`,`Diagnostico`) VALUES (`" + documento_t + "`,`" + nombre_t + "`,`" + apellidos_t + "`,`" + edad_t + "`,`" + estrato_t + "`,`" + grado_t + "`,`" + diagnostico_t +"`)";   
        //String query_insert = "INSERT INTO datos (`Documento`, `Nombre`, `Apellidos`, `Edad`, `Estrato`, `Grado`, `Diagnostico`) VALUES ('"+ documento_t +"','"+ nombre_t +"','"+ apellidos_t +"','"+ edad_t +"','"+ estrato_t +"','"+ grado_t +"','"+ diagnostico_t +"')";
        String query_insert = "INSERT INTO datos VALUES ('"+ documento_t +"','"+ nombre_t +"','"+ apellidos_t +"','"+ edad_t +"','"+ genero_t +"','"+ estrato_t +"','"+ grado_t +"','"+ cdisc +"','"+ diagnostico_t +"','"+ dia_t +"','"+ mes_t +"','"+ anno_t +"')";
        System.out.println(query_insert);
// Verificar que todos los campos estén llenos
        
        
        if (documento.getText().equals("") || nombre.getText().equals("") || edad.getText().equals("") || estrato.getText().equals("") || grado.getText().equals("")) {
            registro.setText("Hay campos sin diligenciar");
        } else
            try{
                cn = con.getCConnection();
                st = cn.createStatement();
//                rs = st.executeQuery(query_insert);
                st.executeUpdate(query_insert);
                registro.setText("Registro Exitoso");
            }catch(SQLException e){
                System.out.println("ERROR");
        }
    }//GEN-LAST:event_InscribirActionPerformed

    private void gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradoActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void annoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SeleccionBateria est;
        est = new SeleccionBateria();
        est.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    private void diaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diaMouseClicked
        // TODO add your handling code here:
        dia.setText("");
    }//GEN-LAST:event_diaMouseClicked

    private void mesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesMouseClicked
        // TODO add your handling code here:
        mes.setText("");
    }//GEN-LAST:event_mesMouseClicked

    private void annoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annoMouseClicked
        // TODO add your handling code here:
        anno.setText("");
    }//GEN-LAST:event_annoMouseClicked

    private void jButton1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ComponentHidden

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inscribir;
    private javax.swing.JTextField anno;
    private javax.swing.JLabel ap;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField diagnostico;
    private javax.swing.JCheckBox discapno;
    private javax.swing.JCheckBox discapsi;
    private javax.swing.JTextField documento;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField estrato;
    private javax.swing.JCheckBox generofemenino;
    private javax.swing.JCheckBox generomasculino;
    private javax.swing.JCheckBox generootro;
    private javax.swing.JTextField grado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel registro;
    // End of variables declaration//GEN-END:variables
}
